# gpio config file

host: localhost
#port: 80
key: 03B0DA5F36984EF98871844175EDCA6F

actions:
    - name: Up
      gpio: 110  #gpio_1
      control: api/printer/printhead
      json: "{ \"command\": \"jog\", \"Z\": 5 }"
    - name: Down
      gpio: 68  #gpio_4
      control: api/printer/printhead
      json: "{ \"command\": \"jog\", \"Z\": -5 }"
